---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: yum update
      yum:
       name: '*'
       state: latest

    - name: Install java
      yum:
       name: java-1.8.0-openjdk
       state: present

    - name: Install python
      yum:
       name: python3
       state: latest

    - name: Download Jenkins release
      action: shell sudo wget -O /etc/yum.repos.d/jenkins.repo \
            https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: Import jenkins key
      action: shell sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Daemon reload
      ansible.builtin.systemd:
       daemon_reload: yes

    - name: Install jenkins
      yum:
       name: jenkins
       state: latest

    - name: start jenkins
      systemd:
        name: jenkins
        state: started
